function measurementType = getCorrectMeasurementCapitalization(measurementType)
%getCorrectMeasurementCapitalization Corrects measurement capitalization
%   [measurementType] = getCorrectMeasurementCapitalization(measurementtype)
%   returns the correct capitalization for a measurement passed to it.  If
%   the measurement is unknown, then it is simply returned

    % Copyright 2010-2012 The MathWorks, Inc.
    %   

    persistent supportedMeasurements;
    
    if isempty(supportedMeasurements)
        % Initialize the list of supported measurements.  Note that these are
        % capitalized correctly.
        supportedMeasurements = {'Voltage',...
                                'Current',...
                                'Thermocouple',...
                                'Accelerometer',...
                                'RTD',...
                                'IEPE',...
                                'Bridge',...
                                'Microphone',...
                                'EdgeCount',...
                                'PulseWidth',...
                                'Frequency',...
                                'Position',...
                                'PulseGeneration',...
                                'InputOnly',...
                                'OutputOnly',...
                                'Bidirectional',...
                                'Audio'};
    end
    
    match = strcmpi(measurementType,supportedMeasurements);
    if any(match)
        % If there's a matching measurement, return the correct capitalization 
        measurementType = supportedMeasurements{match};
    end
end

