function prefspanel
%PREFSPANEL Registers a Data Acquisition Toolbox preferences control panel.
%   PREFSPANEL registers a Preferences Control panel with the MATLAB IDE.

%   Copyright 1998-2005 The MathWorks, Inc.
%   $Revision: 1.2.2.9 $  $Date: 2007/06/18 22:00:32 $


% Register Object-based context menus items in the Workspace Browser.

% Are we on a PC?  Data Acquisition Toolbox (DAT) is a pc only product
if strcmp(computer, 'PCWIN')

    % Define ANALOGINPUT Context menu
    com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
        {'analoginput'},...
        'Explore',...
        {'Display Summary', ...
         'Display Hardware Info', ...
         'Show DAQ Events', ...
         '-', ...
         'DAQ Help'},...
        {'disp($1)', ...
         'daqhwinfo($1); disp(ans)',...
         'showdaqevents($1)', ...
         '-',...
         'daqhelp($1)'});

    % Define ANALOGOUTPUT Context menu - same as analoginputs
    com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerSimilarClassCallbacks(...
        {'analogoutput'}, 'analoginput');

    % Define DIGITALIO Context menu
    com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
        {'digitalio'},...
        'Explore',...
        {'Display Summary', ...
         'Display Hardware Info', ...
         '-', ...
         'DAQ Help'},...
        {'disp($1)', ...
         'daqhwinfo($1); disp(ans)',...
         '-',...
         'daqhelp($1)'});

    % Define DAQDEVICE Context menu
    com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
        {'daqdevice'},...
        'Explore',...
        {'Display Summary', ...
         '-',...
         'DAQ Help'},...
        {'display($1)', ...
         '',...
         'daqhelp($1)'});

    % Define AICHANNEL Context menu
    com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
        {'aichannel'},...
        'Explore',...
        {'Display Summary', ...
         '-', ...
         'DAQ Help'},...
        {'disp($1)', ...
         '',...
         'daqhelp($1)'});

    % Define AOCHANNEL and DIOLINE Context menus - same as aichannel
    com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerSimilarClassCallbacks(...
        {'aochannel', 'dioline'}, 'aichannel');

end
% [EOF]
