function objDACInfo = initDACInfoStruct()

objDACInfo = struct('BoardNames',[],'InstalledBoardIds',[],...
                    'ObjectConstructorName',[],'Control',[],...
                    'dType',[],'sType',[]);