function objDAQ = initDACInfoStruct()

objDAQ = struct('BoardNames',[],'InstalledBoardIds',[],...
                    'ObjectConstructorName',[],'Control',[],...
                    'dType',[],'sType',[]);