classdef (Hidden) StateSession < daq.internal.BaseClass & daq.internal.UserDeleteDisabled
    %StateSession Abstract base class for all Session state objects.
    %   StateSession is an abstract base class for all Session state
    %   objects, declaring all possible methods that a concrete state must
    %   implement, as they might be called.  Many times, the implementation
    %   of "impossible to occur events" in a given state will be an internal error.
    %
    %    This undocumented class may be removed in a future release.
    
    %    Copyright 2010-2011 The MathWorks, Inc.
    %
    
    %   See the Data Acquisition Toolbox CompactDAQ architecture spec, geck
    %   35908, for a complete state charts and descriptions of the states.
    %
    %   This class functions as a State for the Data Acquisition Toolbox
    %   daq.Session object, as defined by "Design Patterns," Booch, et all.
    %   It implements state-specific behaviors on the behalf of the
    %   daq.Session object.  The advantage of this are:
    %
    %   1. The Session object does not have large switch statements or
    %      conditional logic based on current state, reducing the
    %      cyclomatic complexity of the Session class enormously.
    %
    %   2. State operations are 100% internally consistent, reducing the
    %      opportunities for state-based logic errors.  Adding a state is
    %      straightforward.
    %
    %   3. All state based logic for a given state is here in the state
    %      class, allowing easy changes to the state behavior
    
    properties(SetAccess = private,GetAccess = protected)
        Session
    end
    
    % Constructor
    methods
        function obj = StateSession(session)
            obj.Session = session;
        end
    end
    
    methods(Abstract)
        [channel,index] = addChannel(obj,varargin)
        [conn,index] = addTriggerConnection(obj,varargin)
        [conn,index] = addClockConnection(obj,varargin)
        removeChannel(obj,index)
        removeConnection(obj,index)
        errorIfParameterChangeNotOK(obj)
        prepare(obj)
        [data, time, triggerTime] = startForeground(obj)
        startBackground(obj)
        wait(obj,timeout)
        stop(obj,noWait)
        queueOutputData(obj,dataToOutput)
        resetCounters(obj)
        [data,triggerTime] = inputSingleScan(obj)
        outputSingleScan(obj,dataToOutput)
        release(obj)
        processAcquiredData(obj,triggerTime,timestamps,dataAcquired)
        processHardwareTrigger(obj,varargin)
        processOutputEvent(obj,totalScansOutput)
        processHardwareStop(obj,errorException)
        dispSession(obj)
        [result] = getIsLoggingFlag(obj)
        [result] = getIsRunningFlag(obj)
        [result] = getIsWaitingForExternalTriggerFlag(obj)
        checkForTimeout(obj);
    end
    
    methods(Access = protected)
        function resetImpl(obj)
            %resetImpl Handle daq.reset (which is usually delete)
            if isvalid(obj)
                delete(obj)
            end
        end
        
        function doDispWhenRunning(obj)
            % Determine if it should be "scan" or "scans" for Rate
            rateUnitText = obj.getCorrectMsgID( ...
                obj.Session.Rate ,...
                'daq:Session:dispScansUnitsSingular', ...
                'daq:Session:dispScansUnitsPlural');
            
            operationalLengthText = obj.getLocalizedText(...
                'daq:Session:dispOperationRunning',...
                num2str(obj.Session.Rate),...
                rateUnitText);
            
            fprintf(obj.indentText(operationalLengthText,...
                daq.internal.BaseClass.StandardIndent));
            fprintf('\n');
            
            triggerStatusText = '';
            if obj.Session.IsContinuous
                % Continuous operation
                if obj.Session.Channels.countInputChannels > 0
                    
                    numScansAcqUnitText = obj.getCorrectMsgID( ...
                        obj.Session.ScansAcquired ,...
                        'daq:Session:dispScansUnitsSingular', ...
                        'daq:Session:dispScansUnitsPlural');
                    
                    triggerStatusText = [triggerStatusText...
                        obj.getLocalizedText(...
                        'daq:Session:dispScansAcquiredContinuous',...
                        num2str(obj.Session.ScansAcquired),...
                        numScansAcqUnitText) '\n'];
                end
                if obj.Session.Channels.countOutputChannels > 0
                    
                    numScansGenUnitText = obj.getCorrectMsgID( ...
                        obj.Session.ScansOutputByHardware, ...
                        'daq:Session:dispScansUnitsSingular', ...
                        'daq:Session:dispScansUnitsPlural');
                    
                    triggerStatusText = [triggerStatusText...
                        obj.getLocalizedText(...
                        'daq:Session:dispScansGeneratedContinuous',...
                        num2str(obj.Session.ScansOutputByHardware),...
                        numScansGenUnitText) '\n'];
                end
            else
                % Determine if it should be "scan" or "scans" for
                % number of scans
                numScansUnitText = obj.getCorrectMsgID( ...
                    obj.Session.NumberOfScans, ...
                    'daq:Session:dispScansUnitsSingular',...
                    'daq:Session:dispScansUnitsPlural');
                
                % Fixed length operation
                if obj.Session.Channels.countInputChannels > 0
                    triggerStatusText = [triggerStatusText...
                        obj.getLocalizedText(...
                        'daq:Session:dispScansAcquiredFixedLength',...
                        num2str(obj.Session.ScansAcquired),...
                        num2str(obj.Session.NumberOfScans),...
                        numScansUnitText) '\n'];
                end
                if obj.Session.Channels.countOutputChannels > 0
                    triggerStatusText = [triggerStatusText...
                        obj.getLocalizedText(...
                        'daq:Session:dispScansGeneratedFixedLength',...
                        num2str(obj.Session.ScansOutputByHardware),...
                        num2str(obj.Session.NumberOfScans),...
                        numScansUnitText) '\n'];
                end
            end
            fprintf(obj.indentText(triggerStatusText,...
                daq.internal.BaseClass.StandardIndent));
        end
        
        function doDispWhenIdle(obj)
            
            % Determine if it should be "scan" or "scans" for Rate
            rateUnitText = obj.getCorrectMsgID( ...
                obj.Session.Rate ,...
                'daq:Session:dispScansUnitsSingular', ...
                'daq:Session:dispScansUnitsPlural');
            
            % Determine if it should be "scan" or "scans" for
            % number of scans
            numScansUnitText = obj.getCorrectMsgID( ...
                obj.Session.NumberOfScans, ...
                'daq:Session:dispScansUnitsSingular',...
                'daq:Session:dispScansUnitsPlural');
            
            if obj.Session.IsContinuous
                operationalLengthText = obj.getLocalizedText(...
                    'daq:Session:dispOperationLengthContinuous',...
                    num2str(obj.Session.Rate),...
                    rateUnitText);
            else
                
                % Determine if it should be "second" or "seconds"
                durationUnitText = obj.getCorrectMsgID( ...
                    obj.Session.DurationInSeconds, ...
                    'daq:Session:dispDurationUnitsSingular', ...
                    'daq:Session:dispDurationUnitsPlural' );
                
                % Order depends on whether we are running in duration
                % or scan preference
                if obj.Session.IsDurationPreferred
                    if obj.Session.TriggersPerRun > 1
                        operationalLengthText = obj.getLocalizedText(...
                            'daq:Session:dispOperationLengthFixedLengthMultipleTriggers',...
                            num2str(obj.Session.TriggersPerRun),...
                            num2str(obj.Session.DurationInSeconds),...
                            durationUnitText,...
                            num2str(obj.Session.NumberOfScans),...
                            numScansUnitText,...
                            num2str(obj.Session.Rate),...
                            rateUnitText);
                    else
                        operationalLengthText = obj.getLocalizedText(...
                            'daq:Session:dispOperationLengthFixedLength',...
                            num2str(obj.Session.DurationInSeconds),...
                            durationUnitText,...
                            num2str(obj.Session.NumberOfScans),...
                            numScansUnitText,...
                            num2str(obj.Session.Rate),...
                            rateUnitText);
                    end
                else
                    if obj.Session.NumberOfScans == 0
                        % No scans queued
                        if obj.Session.TriggersPerRun > 1
                            operationalLengthText = obj.getLocalizedText(...
                                'daq:Session:dispOperationLengthNoDataQueuedMultipleTriggers',...
                                num2str(obj.Session.TriggersPerRun),...
                                num2str(obj.Session.Rate),...
                                rateUnitText);
                        else
                            operationalLengthText = obj.getLocalizedText(...
                                'daq:Session:dispOperationLengthNoDataQueued',...
                                num2str(obj.Session.Rate),...
                                rateUnitText);
                        end
                    else
                        % Standard "scan preference display"
                        if obj.Session.TriggersPerRun > 1
                            operationalLengthText = obj.getLocalizedText(...
                                'daq:Session:dispOperationLengthFixedLengthMultipleTriggers',...
                                num2str(obj.Session.TriggersPerRun),...
                                num2str(obj.Session.NumberOfScans),...
                                numScansUnitText,...
                                num2str(obj.Session.DurationInSeconds),...
                                durationUnitText,...
                                num2str(obj.Session.Rate),...
                                rateUnitText);
                        else
                            operationalLengthText = obj.getLocalizedText(...
                                'daq:Session:dispOperationLengthFixedLength',...
                                num2str(obj.Session.NumberOfScans),...
                                numScansUnitText,...
                                num2str(obj.Session.DurationInSeconds),...
                                durationUnitText,...
                                num2str(obj.Session.Rate),...
                                rateUnitText);
                        end
                    end
                end
            end
            fprintf(obj.indentText(operationalLengthText,...
                daq.internal.BaseClass.StandardIndent));
            fprintf('\n');
        end
    end
end

