classdef (Hidden) AnalogOutputInfo < daq.AnalogSubsystemInfo
    %AnalogOutputInfo Information about an analog output
    %subsystem on a device
    %    This class is subclassed by adaptors to provide
    %additional information about the analog output subsystem of
    %a device.  They may choose to add custom properties and
    %methods.
    
    % Copyright 2009-2011 The MathWorks, Inc.
    % 
    
    %% -- Protected and private members of the class --
    % Non-public or hidden constructor
    methods (Hidden)
        function obj = AnalogOutputInfo(...
                measurementTypesAvailable,...
                defaultMeasurementType,...
                nativeDataType,...
                AOPhysicalChans,...
                rateLimitInfo,...
                rangesAvailableForDifferential,...
                rangesAvailableForSingleEnded,...
                rangesAvailableForSingleEndedNonReferenced,...
                rangesAvailableForPseudoDifferential,...
                resolution,...
                terminalConfigsAvailableInfo,...
                onDemandOperationsSupported)
    
                %AnalogOutputInfo Information about an analog output
                %subsystem on a device
                % AnalogOutputInfo(...) See daq.SubsystemInfo,
                % daq.ClockedSubsystemInfo, and daq.AnalogSubsystemInfo for
                % parameters.
            
            obj@daq.AnalogSubsystemInfo(...
                measurementTypesAvailable,...
                defaultMeasurementType,...
                nativeDataType,...               
                AOPhysicalChans,...
                rateLimitInfo,...
                rangesAvailableForDifferential,...
                rangesAvailableForSingleEnded,...
                rangesAvailableForSingleEndedNonReferenced,...
                rangesAvailableForPseudoDifferential,...
                resolution,...
                onDemandOperationsSupported);
    
            if isempty(terminalConfigsAvailableInfo) ||...
                    ~isa(terminalConfigsAvailableInfo,'daq.TerminalConfig')
                obj.localizedError('daq:SubsystemInfo:invalidTerminalConfig')
            end
            obj.TerminalConfigsAvailableInfo = terminalConfigsAvailableInfo;
            obj.SubsystemTypeInfo = daq.internal.SubsystemType.AnalogOutput;
        end
    end
    
    % Superclass methods this class implements
    methods (Access = protected)
        function dispText = getDisplayTextImpl(obj)
            % getDisplayTextImpl A display function for this class.  This allows each superclass an opportunity to
            % contribute to the subsystem display.
            dispText = [obj.getLocalizedText('daq:SubsystemInfo:dispAnalogOutputHeader') '\n'...
                obj.indentText(obj.subsystemDisplay(),obj.StandardIndent) '\n'];
        end
    end
    
    properties (SetAccess = private,Hidden)
        %TerminalConfigsAvailableInfo An array of representations of the
        %terminal configs that this subsystem supports.
        TerminalConfigsAvailableInfo
    end
    
end
