classdef (Hidden) CounterInputInfo < daq.CounterSubsystemInfo ...
                                    & daq.CounterInputEdgeCountSubsystemInfo ...
                                    & daq.CounterInputPulseWidthSubsystemInfo ...
                                    & daq.CounterInputPositionSubsystemInfo ...
                                    & daq.CounterInputFrequencySubsystemInfo 
    %CounterInputInfo Information about an analog input
    %subsystem on a device
    %    This class is subclassed by adaptors to provide
    %additional information about the analog input subsystem of
    %a device.  They may choose to add custom properties and
    %methods.
    
    % Copyright 2009-2011 The MathWorks, Inc.
    %   
    
    %% -- Public methods, properties, and events --
    % Read only properties
    properties (SetAccess = private)
    end
    
    %% -- Protected and private members of the class --
    
    % Non-public or hidden constructor
    methods(Hidden)
        function obj = CounterInputInfo(...
                measurementTypesAvailable,...
                defaultMeasurementType,...
                nativeDataType,...                
                CIPhysicalChans,...
                rateLimitInfo,...
                resolution, ...
                activeEdgesAvailable,...
                defaultActiveEdge,...
                defaultMinMaxExpectedFrequency,...
                defaultMinMaxExpectedPulseWidth,...
                onDemandOperationsSupportedEdgeCount,...
                onDemandOperationsSupportedFrequency,...
                onDemandOperationsSupportedPosition,...
                onDemandOperationsSupportedPulseWidth)
            
            %CounterSubsystemInfo Information about a subsystem on a device
            % CounterSubsystemInfo(...,RANGESAVAILABLE,RESOLUTION)
            % See daq.SubsystemInfo and daq.ClockedSubsystemInfo for
            % earlier parameters. A clocked analog
            % subsystem that supports a ranges defined by RANGESAVAILABLE,
            % a vector of daq.Range objects, with resolution of
            % RESOLUTION bits.
            obj@daq.CounterSubsystemInfo( ...
                measurementTypesAvailable,...
                defaultMeasurementType,...
                nativeDataType,...               
                CIPhysicalChans,...
                rateLimitInfo,...
                resolution);
            
            obj@daq.CounterInputEdgeCountSubsystemInfo( ...
                activeEdgesAvailable, ...
                defaultActiveEdge,...
                onDemandOperationsSupportedEdgeCount);
            
            obj@daq.CounterInputFrequencySubsystemInfo( ...
                defaultMinMaxExpectedFrequency,...
                onDemandOperationsSupportedFrequency);
            
            obj@daq.CounterInputPulseWidthSubsystemInfo( ...
                defaultMinMaxExpectedPulseWidth,...
                onDemandOperationsSupportedPulseWidth);
            
            obj@daq.CounterInputPositionSubsystemInfo( ...
                onDemandOperationsSupportedPosition);
            
            obj.SubsystemTypeInfo = daq.internal.SubsystemType.CounterInput;
        end
    end
    
    % Property access methods
    methods
    end
    
    % Hidden read only properties
    properties (SetAccess = private,Hidden)
    end
    
    % Superclass methods this class implements
    methods (Sealed, Access = protected)
        function dispText = getDisplayTextImpl(obj)
            % getDisplayTextImpl A display function for this class.  This allows each superclass an opportunity to
            % contribute to the subsystem display.
            dispText = [obj.getLocalizedText('daq:SubsystemInfo:dispCounterInputHeader') '\n'...
                obj.indentText(obj.subsystemDisplay(),obj.StandardIndent) '\n'];
        end
    end
end

