function scopext(ext)
%SCOPEXT  Register scope extensions for Signal Processing Toolbox.

%   Copyright 2012-2013 The MathWorks, Inc.

r = ext.add(...
    'Sources', 'SPTool', 'sigbrowser.SrcSPTool', ...
    getString(message('signal:sigbrowse:SrcSPTool')));
r.Visible = false;

uiscopes.registerMeasurement(ext, 'acursors', 'uiservices.measurements.ArrayCursors', ...
    'MITimeCursors', 'TTTimeCursors');
uiscopes.registerMeasurement(ext, 'fcursors', 'uiservices.measurements.FrequencyCursors', ...
    'MIFrequencyCursors', 'TTFrequencyCursors');
uiscopes.registerMeasurement(ext, 'signalstats', 'uiservices.measurements.SignalStatistics', ...
    'MISignalStatistics', 'TTSignalStatistics');
uiscopes.registerMeasurement(ext, 'bilevel', 'uiservices.measurements.BilevelMeasurements', ...
    'MIBilevelMeasurements', 'TTBilevelMeasurements');
uiscopes.registerMeasurement(ext, 'peaks', 'uiservices.measurements.PeakFinder', ...
    'MIPeakFinder', 'TTPeakFinder');
uiscopes.registerMeasurement(ext, 'channel', 'uiservices.measurements.ChannelMeasurements', ...
    'MIChannelMeasurements', 'TTChannelMeasurements');
uiscopes.registerMeasurement(ext, 'distortion', 'uiservices.measurements.DistortionMeasurements', ...
    'MIDistortionMeasurements', 'TTDistortionMeasurements');
uiscopes.registerMeasurement(ext, 'ccdf', 'uiservices.measurements.CCDFMeasurements', ...
    'MICCDFMeasurements', 'TTCCDFMeasurements');


% [EOF]
